server:
  port: 8081

spring:
  application:
    name: cloudservice
  cloud:
    config:
      uri: http://${config.server.ip}:${config.server.port}
      name: cloudservice
      profile: ${app.profile:test}

#service discovery url
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#datasource config
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/cloud?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
  username: root
  password: root

#mybatis config
mybatis:
  mapperLocations: classpath:mapper/*.xml